/*
 * File: app/view/MsgBox.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.MsgBox', {
    extend: 'Ext.window.Window',
    alias: 'widget.msgbox',

    requires: [
        'HjHRoziana.view.MsgBoxViewModel',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'msgbox'
    },
    modal: true,
    height: 136,
    padding: 20,
    width: 362,
    title: 'Acknowledgement',

    layout: {
        type: 'hbox',
        align: 'middle',
        pack: 'center'
    },
    items: [
        {
            xtype: 'label',
            flex: 1,
            text: 'Thank you for your order. We will get back to you shortly.'
        }
    ]

});