/*
 * File: app/view/wndBooking.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.wndBooking', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndbooking',

    requires: [
        'HjHRoziana.view.wndBookingViewModel',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'wndbooking'
    },
    height: 650,
    padding: 20,
    width: 800,
    header: false,
    title: '',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            reference: 'MyOrder',
            style: '',
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'image',
                            flex: 1,
                            height: 150,
                            maxHeight: 150,
                            maxWidth: 200,
                            minHeight: 150,
                            minWidth: 200,
                            padding: '0 10 0 0',
                            width: 200,
                            src: '/resources/images/madani/8.png'
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'displayinfotitle',
                                    padding: '10 0 20 0',
                                    text: 'RESERVATION FORM'
                                },
                                {
                                    xtype: 'label',
                                    reference: '',
                                    cls: 'displayinfo',
                                    itemId: 'OrderItem',
                                    padding: '0 0 20 0',
                                    text: 'Order Item: Nasi Al Madani'
                                },
                                {
                                    xtype: 'label',
                                    reference: '',
                                    cls: 'displayinfo',
                                    itemId: 'OrderDate',
                                    padding: '0 0 20 0',
                                    text: 'Date: 20 July 2016'
                                },
                                {
                                    xtype: 'label',
                                    reference: '',
                                    cls: 'displayinfo',
                                    itemId: 'OrderPrice',
                                    text: 'Price: $75 each'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    padding: '10 0 0 0',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            title: 'CUSTOMER DETAILS',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: 20
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Full Name',
                                    labelWidth: 150,
                                    name: 'fullname',
                                    emptyText: 'Hjh Roziana'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        padding: '0 0 6 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            maxWidth: 300,
                                            minWidth: 200,
                                            width: 400,
                                            fieldLabel: 'Contact No',
                                            labelWidth: 150,
                                            name: 'contact',
                                            emptyText: '97123456'
                                        },
                                        {
                                            xtype: 'textfield',
                                            maxWidth: 500,
                                            minWidth: 500,
                                            width: 500,
                                            fieldLabel: 'Email',
                                            name: 'email',
                                            emptyText: 'john@doe.com'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Address',
                                    labelWidth: 150,
                                    name: 'address',
                                    emptyText: 'Blk XX, Woodlands'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'h3',
                            title: 'ORDER DETAILS',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: 20
                            },
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'evt_id',
                                    fieldLabel: 'Label',
                                    name: 'evt_id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'evt_type',
                                    fieldLabel: 'Label',
                                    name: 'evt_type'
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    maxWidth: 250,
                                    minWidth: 250,
                                    width: 250,
                                    fieldLabel: 'Quantity',
                                    labelWidth: 150,
                                    name: 'qty',
                                    minValue: 1
                                },
                                {
                                    xtype: 'textareafield',
                                    fieldLabel: 'Order Remarks',
                                    labelWidth: 150,
                                    name: 'dtime',
                                    emptyText: 'Self-Pickup at 2pm'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    itemId: 'cnfrmbooking',
                    scale: 'large',
                    text: 'Confirm Order'
                },
                {
                    xtype: 'button',
                    itemId: 'cancelbooking',
                    scale: 'large',
                    text: 'Cancel'
                }
            ]
        }
    ]

});