/*
 * File: app/store/Events.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Events', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Event',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Events',
            autoLoad: true,
            model: 'MyApp.model.Event',
            proxy: me.processMyAjaxProxy({
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    rootProperty: 'data'
                }
            })
        }, cfg)]);
    },

    processMyAjaxProxy: function(config) {
        config.api = {
            create: "/php/addevent.php",
            read: "/php/getall.php",
            update: "/php/updateevent.php",
            destroy: "/php/deleteevent.php"
        };
        return config;
    }

});