/*
 * File: app/view/EventEntry.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EventEntry', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.evententry',

    requires: [
        'MyApp.view.EventEntryViewModel',
        'MyApp.view.EventEntryViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.view.Table'
    ],

    controller: 'evententry',
    viewModel: {
        type: 'evententry'
    },
    width: 500,
    bodyBorder: true,
    title: 'Food Catering',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            reference: 'myform',
            bodyBorder: true,
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    maxWidth: 250,
                    minWidth: 250,
                    width: 250,
                    fieldLabel: 'Event Date',
                    name: 'evt_date',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    maxWidth: 250,
                    minWidth: 250,
                    width: 250,
                    fieldLabel: 'Serving Type',
                    name: 'evt_type',
                    emptyText: 'ALMADANI',
                    displayField: 'evt_type',
                    store: 'EvtType',
                    valueField: 'evt_type',
                    forceSelection: true,
                    allowBlank: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    maxWidth: 200,
                    minWidth: 200,
                    width: 200,
                    fieldLabel: 'Max Qty',
                    name: 'evt_qty',
                    emptyText: '40'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    maxWidth: 200,
                    minWidth: 200,
                    width: 200,
                    fieldLabel: 'Price $',
                    name: 'evt_price',
                    emptyText: '75.00'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Remarks',
                    name: 'evt_remarks'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            reference: 'addentry',
                            itemId: 'AddEntry',
                            text: 'Add New',
                            formBind: true
                        },
                        {
                            xtype: 'button',
                            reference: 'removeEntry',
                            disabled: true,
                            itemId: 'removeEntry',
                            text: 'Delete Entry'
                        },
                        {
                            xtype: 'button',
                            itemId: 'clearform',
                            text: 'Clear Form'
                        },
                        {
                            xtype: 'button',
                            itemId: 'refresh',
                            text: 'Refresh'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            reference: 'evtgrid',
            bodyBorder: true,
            title: 'Slot Date',
            forceFit: true,
            store: 'Events',
            columns: [
                {
                    xtype: 'gridcolumn',
                    maxWidth: 120,
                    minWidth: 120,
                    width: 120,
                    dataIndex: 'evt_date',
                    formatter: 'date("D d-M-Y")',
                    text: 'DATE'
                },
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '{evt_type}<br />',
                        '{evt_remarks}'
                    ],
                    dataIndex: 'evt_type',
                    text: 'ITEM'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 60,
                    minWidth: 60,
                    width: 60,
                    align: 'center',
                    dataIndex: 'evt_qty',
                    text: 'MAX QTY'
                },
                {
                    xtype: 'templatecolumn',
                    maxWidth: 60,
                    minWidth: 60,
                    tpl: [
                        '${evt_price}'
                    ],
                    width: 60,
                    dataIndex: 'evt_price',
                    text: 'PRICE'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 60,
                    minWidth: 60,
                    width: 60,
                    align: 'center',
                    dataIndex: 'qtybook',
                    text: 'QTY BOOK'
                }
            ]
        }
    ]

});