/*
 * File: app/view/MyForm1.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyForm1', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform1',

    requires: [
        'MyApp.view.MyForm1ViewModel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myform1'
    },
    height: 250,
    margin: 0,
    padding: '',
    width: 400,
    defaults: {
        margin: 10
    },
    bodyPadding: 10,
    title: 'User Credentials',

    items: [
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Name',
            name: 'name'
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Password',
            name: 'password',
            inputType: 'password'
        },
        {
            xtype: 'button',
            itemId: 'login',
            text: 'Login'
        }
    ]

});