/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'MyApp.view.MyForm1',
        'MyApp.view.EventEntry',
        'MyApp.view.CustDetail',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'myviewport'
    },
    padding: '',
    layout: 'border',

    items: [
        {
            xtype: 'toolbar',
            region: 'north',
            height: 80,
            items: [
                {
                    xtype: 'label',
                    cls: 'title',
                    text: 'Hjh Roziana\'s Catering'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'south',
            height: 40,
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'label',
                    text: 'Copyright Hjh Roziana\'s Catering 2016'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'landing',
            layout: 'card',
            items: [
                {
                    xtype: 'container',
                    itemId: 'loginpanel',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'myform1',
                            border: true,
                            bodyBorder: true
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'mainbody',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'evententry',
                            margin: 10
                        },
                        {
                            xtype: 'custdetail',
                            flex: 1,
                            margin: 10
                        }
                    ]
                }
            ]
        }
    ]

});