/*
 * File: app/controller/MainMenu.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.controller.MainMenu', {
    extend: 'Ext.app.Controller',

    stores: [
        'bookings'
    ],

    refs: {
        mainbody: 'viewport container[itemId=mainBody]',
        specificbooking: 'pagespecificbooking'
    },
    routes: {
        'almadani': 'showAlMadani',
        'ambeng': 'showAmbeng',
        'laukraya': 'showLaukRaya'
    },
    control: {
        "button[itemId=mnuWeddingCatering]": {
            click: 'onWeddingCateringClick'
        },
        "button[itemId=mnuChefHome]": {
            click: 'onChefHomeClick'
        },
        "button[itemId=mnuNasiAmbeng]": {
            click: 'onNasiAmbengClick'
        },
        "button[itemId=mnuAlMadani]": {
            click: 'onAlMadaninClick'
        },
        "button[itemId=mnuBerlian]": {
            click: 'onBerlianClick'
        },
        "button[itemId=mnuHome]": {
            click: 'onHomeClick'
        },
        "button[itemId=mnuAbout]": {
            click: 'onAboutClick'
        },
        "button[itemId=mnuBooking]": {
            click: 'onBookingClick'
        },
        "button[itemId=mnuIntan]": {
            click: 'onIntanClick'
        },
        "button[itemId=mnuPermata]": {
            click: 'onPermataClick'
        },
        "button[itemId=mnuBookingAmbeng]": {
            click: 'onBookingAmbengClick'
        },
        "button[itemId=mnuBookingAlMadani]": {
            click: 'onBookingAlMadaninClick'
        },
        "button[itemId=reqtocontact]": {
            click: 'onReqToContactClick'
        },
        "gridpanel": {
            cellclick: 'onGridpanelCellClick'
        },
        "button[itemId=cnfrmbooking]": {
            click: 'onCnfrmBookingClick'
        },
        "button[itemId=enquiry]": {
            click: 'onEnquiryClick'
        },
        "button[itemId=intanpdf]": {
            click: 'onIntanPDFClick'
        },
        "button[itemId=berlianpdf]": {
            click: 'onBerlianPDFClick'
        },
        "button[itemId=permatapdf]": {
            click: 'onPermataPDFClick'
        },
        "button[itemId=cancelbooking]": {
            click: 'onCancelButtonClick'
        }
    },

    onWeddingCateringClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(2);

        $('.wedding').slick({
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
        });

        $('.wedding').on('click', function(event, slick, direction) {

            var wnd = Ext.WindowManager.get('popup');
            if(!wnd)
                wnd = Ext.create("HjHRoziana.view.Page.PopOut");
            img = wnd.down("image");

            img.setSrc(event.target.src.replace('-th',''));
            console.log(img.src);
            wnd.show();
            Ext.defer(function() {
                wnd.destroy();
            }, 5000);
        });
        window.scrollTo(0,0);
    },

    onChefHomeClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(5);

        $('.chefathome').slick({
          slidesToShow: 5,
          slidesToScroll: 1,
          autoplay: true,
          autoplaySpeed: 2000,
        });

        $('.chefathome').on('click', function(event, slick, direction) {
            var wnd = Ext.WindowManager.get('popup');
            if(!wnd)
                wnd = Ext.create("HjHRoziana.view.Page.PopOut");
            img = wnd.down("image");

            img.setSrc(event.target.src.replace('-th',''));
            console.log(img.src);
            wnd.show();
            Ext.defer(function() {
                wnd.destroy();
            }, 5000);
        });
        window.scrollTo(0,0);
    },

    onNasiAmbengClick: function(button, e, eOpts) {
        this.showAmbeng();

    },

    onAlMadaninClick: function(button, e, eOpts) {
        this.showAlMadani();

    },

    onBerlianClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();
        bdy.getLayout().setActiveItem(11);
    },

    onHomeClick: function(button, e, eOpts) {
                var bdy = this.getMainbody();

                bdy.getLayout().setActiveItem(0);

        window.scrollTo(0,0);
    },

    onAboutClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();
        bdy.getLayout().setActiveItem(1);

        window.scrollTo(0,0);
    },

    onBookingClick: function(button, e, eOpts) {

                        var bdy = this.getMainbody();

                        bdy.getLayout().setActiveItem(6);
    },

    onIntanClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();
        bdy.getLayout().setActiveItem(9);
    },

    onPermataClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();
        bdy.getLayout().setActiveItem(10);
    },

    onBookingAmbengClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(8);

        pnl = this.getSpecificbooking();
        console.log(pnl);
        selType = pnl.down("label[itemId=selectedType]");
        console.log(selType);
        selType.setText("NASI AMBENG RESERVATION");
        var store = this.getBookingsStore();
        console.log(store);

        store.load({
            params: {
                evttype : 'AMBENG'
            }
        });


        window.scrollTo(0,0);
    },

    onBookingAlMadaninClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(8);

        pnl = this.getSpecificbooking();
        selType = pnl.down("label[itemId=selectedType]");
        selType.setText("NASI AL-MADANI RESERVATION");

        var store = this.getBookingsStore();
        console.log(store);

        store.load({
            params: {
                evttype : 'ALMADANI'
            }
        });

        window.scrollTo(0,0);
    },

    onReqToContactClick: function(button, e, eOpts) {
        var bdy = this.getMainbody();
        bdy.getLayout().setActiveItem(7);
        window.scrollTo(0,0);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        /*
        var pnl = this.getSpecificbooking(),
            selDate = pnl.down("displayfield[itemId=selectedDate]"),
            evtid = pnl.down("hiddenfield[name=evt_id]"),
            maxqty = pnl.down("numberfield[name=qty]");

        console.log(record.data);

        evtid.setValue(record.data.evt_id);
        var st = record.data.evt_date;
        var dt = new Date(st);

        maxqty.setMaxValue(record.data.evt_qty);
        selDate.setValue(dt.toDateString());
        */

        var wnd = Ext.create("HjHRoziana.view.wndBooking"),
            OrderItem = wnd.down("label[itemId=OrderItem]"),
            OrderDate = wnd.down("label[itemId=OrderDate]"),
            OrderPrice = wnd.down("label[itemId=OrderPrice]"),
            EvtId = wnd.down("hidden[itemId=evt_id]"),
            EvtType = wnd.down("hidden[itemId=evt_type]");

        OrderItem.setText("Item: " + record.data.evt_type);
        OrderDate.setText("Date: " + record.data.evt_date);
        OrderPrice.setText("Price: $" + record.data.evt_price);
        EvtId.setValue(record.data.evt_id);
        EvtType.setValue(record.data.evt_type);
        console.log(record);
        console.log(OrderDate);
        wnd.show();
    },

    onCnfrmBookingClick: function(button, e, eOpts) {
        var me = this,
            wnd = button.up("window"),
            values = wnd.down("form").getForm().getValues();

         Ext.Msg.show({
             title:'Confirm Reservation?',
             message: 'You are making a reservation. Would you like to confirmed?',
             buttons: Ext.Msg.YESNO,
             icon: Ext.Msg.QUESTION,
             fn: function(btn) {
                 if (btn === 'yes') {
                     var myObj = values;
                     console.log(myObj);

                     // Send Info to Server
                     Ext.Ajax.request({
                         method: "POST",
                         url: HjHRoziana.Global.config.myurl + 'booking.php',
                         params: {
                             ajax_req: Ext.util.JSON.encode(myObj)
                         },
                         success: function(response, opts) {
                             //var obj = Ext.decode(response.responseText);
                             //console.dir(obj);
                             //console.log(response.responseText);
                         },
                         failure: function(response, opts) {
                             console.log('server-side failure with status code ' + response.status);
                         }
                     });

                     // Complete: Send TQ
                     var myMsg = Ext.create('HjHRoziana.view.MsgBox').show();

                     Ext.defer(function() {
                         myMsg.destroy();
                     }, 3000);

                     wnd.close();
                     var store = this.getBookingsStore();
                    console.log(store);

                    store.load({
                        params: {
                            evttype : values.evt_type
                        }
                    });
                     /*
                     if(record.data.evt_type == "ALMADANI") {
                         me.showAlMadani();
                     } else {
                         me.showAmbeng();
                     }
                     */
                 }
             }
         });


        /*
        var me = this,
            ref = button.up("fieldcontainer"),
            fullname = ref.down("textfield[name=fullname]"),
            email = ref.down("textfield[name=email]"),
            contact = ref.down("textfield[name=contact]"),
            evt_id = ref.down("hiddenfield[name=evt_id]"),
            address = ref.down("textarea[name=address]"),
            qty = ref.down("numberfield[name=qty]"),
            deliverytime = ref.down("textfield[name=deliverytime]"),
            pnl = this.getSpecificbooking(),
            selType = pnl.down("label[itemId=selectedType]"),
            selDate = pnl.down("displayfield[itemId=selectedDate]");

        if(selDate.value === "") {
            Ext.Msg.alert('Reminder', 'Please select a reservation date');
        } else {

            Ext.Msg.show({
                title:'Confirm Reservation?',
                message: 'You are making a reservation. Would you like to confirmed?',
                buttons: Ext.Msg.YESNO,
                icon: Ext.Msg.QUESTION,
                fn: function(btn) {
                    if (btn === 'yes') {
                        var myObj = {
                            "fullname" : fullname.value,
                            "email" : email.value,
                            "contact" : contact.value,
                            "evt_id" : evt_id.value,
                            "address" : address.value,
                            "qty" : qty.value,
                            "dtime" : deliverytime.value
                        };
                        console.log(myObj);

                        // Send Info to Server
                        Ext.Ajax.request({
                            method: "POST",
                            url: 'http://mhds.diskstation.me/HjhRoziana/php/booking.php',
                            params: {
                                ajax_req: Ext.util.JSON.encode(myObj)
                            },
                            success: function(response, opts) {
                                //var obj = Ext.decode(response.responseText);
                                //console.dir(obj);
                                //console.log(response.responseText);
                            },

                            failure: function(response, opts) {
                                console.log('server-side failure with status code ' + response.status);
                            }
                        });

                        // Complete: Send TQ
                        var myMsg = Ext.create('HjHRoziana.view.MsgBox').show();

                        Ext.defer(function() {
                            myMsg.destroy();
                        }, 3000);

                        if(selType.text == "NASI AL-MADANI RESERVATION") {
                            me.showAlMadani();
                        } else {
                            me.showAmbeng();
                        }

                    } else if (btn === 'no') {
                        console.log('No pressed');
                    }
                }
            });
        }
        */
    },

    onEnquiryClick: function(button, e, eOpts) {
        var ref = button.up("fieldcontainer"),
            fullname = ref.down("textfield[name=fullname]"),
            email = ref.down("textfield[name=email]"),
            contact = ref.down("textfield[name=contact]"),
            eventdate = ref.down("textarea[name=eventdate]");

        var myObj = {
            "fullname" : fullname.value,
            "email" : email.value,
            "contact" : contact.value,
            "eventdate" : eventdate.value
        };

        Ext.Ajax.request({
            method: "POST",
            url: HjHRoziana.Global.config.myurl + 'enquiry.php',
            params: {
                ajax_req: Ext.util.JSON.encode(myObj)
            },
            success: function(response, opts) {
                //var obj = Ext.decode(response.responseText);
                //console.dir(obj);
                //console.log(response.responseText);
            },

            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });

        // Complete: Send TQ
        var myMsg = Ext.create('HjHRoziana.view.MsgBox').show();

        Ext.defer(function() {
            myMsg.destroy();
        }, 3000);

        fullname.setValue("");
        email.setValue("");
        contact.setValue("");
        eventdate.setValue("");

        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(2);

        $('.wedding').slick({
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
        });

        $('.wedding').on('click', function(event, slick, direction) {

            var wnd = Ext.WindowManager.get('popup');
            if(!wnd)
                wnd = Ext.create("HjHRoziana.view.Page.PopOut");
            img = wnd.down("image");

            img.setSrc(event.target.src.replace('-th',''));
            console.log(img.src);
            wnd.show();
            Ext.defer(function() {
                wnd.destroy();
            }, 5000);
        });
        window.scrollTo(0,0);
    },

    onIntanPDFClick: function(button, e, eOpts) {

        wnd=Ext.create('HjHRoziana.view.DisplayPDF',
        {
            title: "Intan Wedding Catering Package",
            width: '75%',
            height: '75%',
            html: '<iframe src="resources/images/packages/Intan Package.pdf" style="width:100%; height: 100%;" frameborder="no"></iframe>'
        });

        wnd.show();
    },

    onBerlianPDFClick: function(button, e, eOpts) {
        wnd=Ext.create('HjHRoziana.view.DisplayPDF',
        {
            title: "Berlian Wedding Catering Package",
            width: '75%',
            height: '75%',
            html: '<iframe src="resources/images/packages/Berlian Package.pdf" style="width:100%; height: 100%;" frameborder="no"></iframe>'
        });

        wnd.show();
    },

    onPermataPDFClick: function(button, e, eOpts) {
        wnd=Ext.create('HjHRoziana.view.DisplayPDF',
        {
            title: "Permata Wedding Catering Package",
            width: '75%',
            height: '75%',
            html: '<iframe src="resources/images/packages/Permata Package.pdf" style="width:100%; height: 100%;" frameborder="no"></iframe>'
        });

        wnd.show();
    },

    onCancelButtonClick: function(button, e, eOpts) {
        button.up("window").close();
    },

    showAlMadani: function() {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(4);

        $('.madani').slick({
          slidesToShow: 5,
          slidesToScroll: 1,
          autoplay: true,
          autoplaySpeed: 2000,
        });

        $('.madani').on('click', function(event, slick, direction) {

            var wnd = Ext.WindowManager.get('popup');
            if(!wnd)
                wnd = Ext.create("HjHRoziana.view.Page.PopOut");
            img = wnd.down("image");

            img.setSrc(event.target.src.replace('-th',''));
            console.log(img.src);
            wnd.show();
            Ext.defer(function() {
                wnd.destroy();
            }, 5000);
        });
        window.scrollTo(0,0);
    },

    showAmbeng: function() {
        var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(3);

        $('.ambeng').slick({
          slidesToShow: 5,
          slidesToScroll: 1,
          autoplay: true,
          autoplaySpeed: 2000,
        });

        $('.ambeng').on('click', function(event, slick, direction) {

            var wnd = Ext.WindowManager.get('popup');
            if(!wnd)
                wnd = Ext.create("HjHRoziana.view.Page.PopOut");
            img = wnd.down("image");

            img.setSrc(event.target.src.replace('-th',''));
            console.log(img.src);
            wnd.show();

            Ext.defer(function() {
                wnd.destroy();
            }, 5000);
        });
        window.scrollTo(0,0);
    },
    
    showLaukRaya: function() {
    	var bdy = this.getMainbody();

        bdy.getLayout().setActiveItem(8);

        pnl = this.getSpecificbooking();
        console.log(pnl);
        selType = pnl.down("label[itemId=selectedType]");
        console.log(selType);
        selType.setText("LAUK RAYA RESERVATION");
        var store = this.getBookingsStore();
        console.log(store);

        store.load({
            params: {
                evttype : 'LAUKRAYA'
            }
        });


        window.scrollTo(0,0);
    }

});
