/*
 * File: app/view/Page/About.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.About', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pageabout',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel5',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'pageabout'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-about.png);\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 880px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 650,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            padding: '130 0 0 0',
                            width: '50%',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'image',
                                    height: 450,
                                    margin: '-50 0 30 0',
                                    maxHeight: 450,
                                    maxWidth: 500,
                                    minHeight: 450,
                                    minWidth: 500,
                                    width: 500,
                                    src: 'resources/images/logo-about3.png'
                                },
                                {
                                    xtype: 'image',
                                    height: 140,
                                    hidden: true,
                                    maxHeight: 140,
                                    maxWidth: 140,
                                    minHeight: 140,
                                    minWidth: 140,
                                    width: 140,
                                    src: 'resources/images/logo-about.png'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            padding: '130 0 0 0',
                            width: '50%',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'desc',
                                    html: '<p>It’s a family home based business that started out since 1997. We are the third generation to explore and inherit this culinary expertise. We provide catering services for close friends and relative back then. Slowly thru words of mouth and recommendations. We stand where we are right now and we are still revising and improving ourselves.</p> <p>We had done private and personal functions for VIPs and their families.</p> <p>We do events such as Mawlid Rasulullah saw, Wedding services, home catering for Private functions, Dulang services and Company events suits to their needs.</p> <p><span style="font-style:italic; font-size:24px;">It is our passion to serve you with our heart and soul.</span></p>',
                                    width: '80%'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});