/*
 * File: app/view/Page/Booking.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.Booking', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagebooking',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel4',
        'Ext.container.Container',
        'Ext.form.Label',
        'Ext.form.field.Date'
    ],

    viewModel: {
        type: 'pagebooking'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-booking.png);\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 880px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 859,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            cls: 'txtsp',
                            html: 'DO NOT MISS THIS<br />OPPORTUNITY',
                            margin: '260 0 0 0',
                            width: 409,
                            text: 'DO NOT MISS THIS'
                        },
                        {
                            xtype: 'label',
                            cls: 'txtsp1',
                            html: 'DO NOT MISS THIS<br />OPPORTUNITY',
                            width: 409,
                            text: 'OPPORTUNITY'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: '40 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '0 50 0 0',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            cls: 'custom',
                                            margin: '0 0 20 0 ',
                                            width: 238,
                                            emptyText: '01-01-2016'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            emptyText: '14:00'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            margin: '0 0 20 0 ',
                                            width: 262,
                                            emptyText: '120 Pax'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            emptyText: 'Your Name Please'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});