/*
 * File: app/view/Page/CaterBooking.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.CaterBooking', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagecaterbooking',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel7',
        'Ext.form.Label',
        'Ext.form.FieldContainer',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pagecaterbooking'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-booking.png);\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 880px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 859,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            cls: 'h4',
                            height: 40,
                            html: 'WEDDING CATERING / GENERAL ENQUIRIES',
                            margin: '50 0 0 0'
                        },
                        {
                            xtype: 'label',
                            margins: '',
                            cls: 'desc',
                            html: '',
                            margin: '0 0 20 0',
                            text: 'Thank You For Your Interest In Our Catering Packages'
                        },
                        {
                            xtype: 'label',
                            cls: 'desc',
                            html: '',
                            margin: '0 0 20 0',
                            text: 'Do Give Us A Call'
                        },
                        {
                            xtype: 'label',
                            cls: 'h4',
                            html: '',
                            margin: '',
                            text: '+65 9825 9847'
                        },
                        {
                            xtype: 'label',
                            cls: 'h5',
                            html: '',
                            margin: '7 0 20 0',
                            text: 'HJH ROZIANA'
                        },
                        {
                            xtype: 'label',
                            cls: 'h4',
                            html: '',
                            margin: '',
                            text: '+65 9732 0454'
                        },
                        {
                            xtype: 'label',
                            cls: 'h5',
                            html: '',
                            margin: '7 0 20 0',
                            text: 'HJ OSMAN'
                        },
                        {
                            xtype: 'label',
                            cls: 'desc',
                            html: '',
                            margin: '0 0 20 0',
                            text: 'Or fill up the form and we will get back to you within 24 hours'
                        },
                        {
                            xtype: 'fieldcontainer',
                            margin: '10 0 0 0',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            margin: '0 15 0 0',
                                            width: 263,
                                            name: 'fullname',
                                            emptyText: 'Your Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            margin: '0 15 0 0',
                                            width: 263,
                                            name: 'email',
                                            emptyText: 'Your Email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'custom',
                                            margin: '0 15 0 0',
                                            width: 262,
                                            name: 'contact',
                                            emptyText: 'Contact Number(s)'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    width: 400,
                                    fieldLabel: '',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            cls: 'custom',
                                            width: 238,
                                            name: 'eventdate',
                                            emptyText: 'Enquiry'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    height: 35,
                                    itemId: 'enquiry',
                                    margin: '25 0 0 0',
                                    scale: 'large',
                                    text: 'SUBMIT ENQUIRY'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});