/*
 * File: app/view/Page/ChefatHome.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.ChefatHome', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagechefathome',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel3',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pagechefathome'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-chef@home.png);\n\n\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 1400px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    width: '60%'
                },
                {
                    xtype: 'container',
                    width: '40%',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 90,
                            margin: '30 0 0 0',
                            width: 400,
                            src: 'resources/images/tt-chef@home.png'
                        },
                        {
                            xtype: 'label',
                            flex: 1,
                            cls: 'h4',
                            height: 40,
                            hidden: true,
                            margin: '30 0 0 0',
                            text: 'NASI AMBENG'
                        },
                        {
                            xtype: 'label',
                            cls: 'desc',
                            margin: '10 0 0 0',
                            width: '70%',
                            text: 'For those who wants to try casual dining at home, we offer three or four course meal for your family or friends. We offer three different main course to suit your taste buds. We will make the ambience of your home as though you are having it at a restaurant. Our Chef, Muhamad Syafiq, a graduate from Western Culinary School with Institute of Paul Bocuse and ITE West College will whip up the cuisine right in your kitchen. Using high quality meats, seafood and vegetables to create sensational taste buds.'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'reqtocontact',
                            margin: '40 0 0 0',
                            scale: 'large',
                            text: 'ENQUIRE'
                        },
                        {
                            xtype: 'image',
                            height: 55,
                            margin: '40 0 0 0',
                            width: 150,
                            src: 'resources/images/tt-menu.png'
                        },
                        {
                            xtype: 'label',
                            cls: 'desclist',
                            height: 784,
                            html: '<ul> <li class="tt">APPETIZER </li> <li>Caesar salad with poached egg </li> <li>Pan-seared Scallop with Mango salsa & lemon vinaigrette  </li> <li class="bl">&nbsp;</li> <li class="tt">SOUP</li> <li>Potato & Leek soup top with croutons</li> <li>Wild mushroom soup</li> <li class="bl">&nbsp;</li> <li class="tt">MAIN COURSE</li> <li>Asian crusted Rack of Lamb with sweet potato mash & pineapple sauce</li> <li>Chicken roulade stuffed with spinach & orange cream sauce </li> <li>Pan seared salmon with fennel purre & potato gratin </li> <li class="bl">&nbsp;</li> <li class="tt">DESSERT</li> <li>Crème brulee infused with lime leave & pistachio </li> </ul>',
                            margin: '10 0 0 0',
                            maxWidth: 500,
                            minWidth: 200,
                            style: 'text-align:left !important;',
                            width: '75%'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'ctnpricolor',
            height: 250,
            html: [
                '<div class="chefathome">',
                '<div><img src="resources/images/chefathome/1-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/2-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/3-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/4-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/5-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/6-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/7-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/8-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/9-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/10-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/11-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/12-th.png" width="230" /></div>',
                '<div><img src="resources/images/chefathome/13-th.png" width="230" /></div>',
                '</div>'
            ],
            padding: 10,
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        }
    ]

});