/*
 * File: app/view/Page/Home.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.Home', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagehome',

    requires: [
        'HjHRoziana.view.Page.HomeViewModel',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pagehome'
    },
    border: false,
    cls: 'bg100',
    minHeight: 800,
    bodyStyle: 'background:#131414;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            cls: 'bg',
            style: 'background-image:url(resources/images/bg-home.png);\n\n\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: auto;\n    min-height:100%;\n    padding-top:10px;',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 600,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            flex: 1,
                            height: 380,
                            margin: '30 0 0 0',
                            maxHeight: 380,
                            maxWidth: 500,
                            minHeight: 380,
                            minWidth: 500,
                            width: 500,
                            src: 'resources/images/logo-home.png'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'tbrhome',
                    height: 100,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            cls: 'tbrtrans',
                            minHeight: 70,
                            items: [
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    margin: '0 30 0 0',
                                    width: 90,
                                    text: 'ABOUT'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    itemId: 'mnuWeddingCatering',
                                    margin: '0 30 0 0',
                                    width: 182,
                                    text: 'WEDDING CATERING'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    itemId: 'mnuNasiAmbeng',
                                    margin: '0 30 0 0',
                                    width: 141,
                                    text: 'NASI AMBENG'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    itemId: 'mnuAlMadani',
                                    margin: '0 30 0 0',
                                    width: 160,
                                    text: 'NASI AL-MADANI'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    itemId: 'mnuChefHome',
                                    margin: '0 30 0 0',
                                    width: 141,
                                    text: 'CHEF@HOME'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btnmainnav',
                                    itemId: 'reqtocontact',
                                    width: 108,
                                    text: 'ENQUIRY'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});