/*
 * File: app/view/Page/NasiMadani.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.NasiMadani', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagenasimadani',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel1',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pagenasimadani'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            style: 'background-image:url(resources/images/bg-nasimadani.png);\n\n\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 880px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 859,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 90,
                            margin: '30 0 0 0',
                            width: 513,
                            src: 'resources/images/tt-nasimadani.png'
                        },
                        {
                            xtype: 'label',
                            flex: 1,
                            cls: 'h4',
                            height: 40,
                            hidden: true,
                            margin: '30 0 0 0',
                            text: 'NASI AMBENG'
                        },
                        {
                            xtype: 'label',
                            cls: 'desc',
                            margin: '10 0 0 0',
                            width: '35%',
                            text: 'Is our signature dish a fusion of Arab, Indian and Western cuisine. We use different method of cooking with top-niche Rack of Lamb and Lamb Shank from Australia, we cooked the lamb using a pressure cooker and we baked the kebab to make the kebab tender and juicy. We used high quality ingredients like thyme and rosemary, it’s a herb that match perfectly with the lamb with that we produce this wonderful platter. We also provide to those who are interested to try our wedding package Mediterranean style wedding.'
                        },
                        {
                            xtype: 'label',
                            cls: 'desclist',
                            html: 'Dalcha Sayur<br />Braised Lamb Shank<br />Braised Rack of Lamb<br />Arugula Salad<br />Honey Roasted Chicken<br />Beef Kofta kebab<br />Summer Salad<br />Mint Sauce<br />Coriander Sauce<br /> Potato Samosa',
                            margin: '35 0 0 0',
                            width: 389
                        },
                        {
                            xtype: 'button',
                            height: 35,
                            itemId: 'mnuBookingAlMadani',
                            margin: '30 0 0 0',
                            maxHeight: 35,
                            minHeight: 35,
                            scale: 'large',
                            text: 'ORDER NOW!'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'ctnpricolor',
            height: 250,
            html: [
                '<div class="madani">',
                '<div><img src="resources/images/madani/1-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/2-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/3-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/4-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/5-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/6-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/7-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/8-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/9-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/10-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/11-th.png" width="230" /></div>',
                '<div><img src="resources/images/madani/12-th.png" width="230" /></div>',
                '</div>'
            ],
            padding: 10,
            width: '100%',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            }
        }
    ]

});