/*
 * File: app/view/Page/NasiAmbeng.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.NasiAmbeng', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagenasiambeng',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pagenasiambeng'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-nasiambeng.png);\n\n\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 920px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 900,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 90,
                            margin: '30 0 0 0',
                            width: 400,
                            src: 'resources/images/tt-nasiambeng.png'
                        },
                        {
                            xtype: 'label',
                            flex: 1,
                            cls: 'h4',
                            height: 40,
                            hidden: true,
                            margin: '30 0 0 0',
                            text: 'NASI AMBENG'
                        },
                        {
                            xtype: 'label',
                            cls: 'desc',
                            margin: '10 0 0 0',
                            width: 409,
                            text: 'This is our hot seller - Nasi Ambeng. Using recipe handed down from generation to generation. It consist of 16 dishes serve in one big platter. The objective is to allow your love ones to come together sharing, good and delicious home cooked food.'
                        },
                        {
                            xtype: 'label',
                            cls: 'desclist',
                            html: 'Rendang<br /> Ayam Lemak Chili Api<br /> Ikan Belado<br /> Sambal Goreng<br /> Terung Sambal<br /> Urap<br /> Serunding<br /> Tahu goreng<br /> Paru goreng<br /> Tempeh berempah<br /> Telur kunyit<br /> Begedel<br /> Sambal belachan<br /> Sambal kicap<br /> Sohun goring<br /> Nasi putih',
                            margin: '25 0 10 0',
                            width: 389
                        },
                        {
                            xtype: 'button',
                            cls: '',
                            height: 35,
                            itemId: 'mnuBookingAmbeng',
                            margin: '15 0 0 0',
                            maxHeight: 35,
                            minHeight: 35,
                            scale: 'large',
                            text: 'ORDER NOW'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'ctnpricolor',
            height: 250,
            html: [
                '<div class="ambeng">',
                '<div><img src="resources/images/ambeng/1-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/2-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/3-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/5-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/6-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/7-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/8-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/9-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/10-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/11-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/12-th.png" width="230" /></div>',
                '<div><img src="resources/images/ambeng/13-th.png" width="230" /></div>',
                '</div>'
            ],
            padding: 10,
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        }
    ]

});