/*
 * File: app/view/Page/PopOut.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.PopOut', {
    extend: 'Ext.window.Window',
    alias: 'widget.page.popout',

    requires: [
        'HjHRoziana.view.Page.PopOutViewModel',
        'Ext.Img'
    ],

    viewModel: {
        type: 'page.popout'
    },
    height: 500,
    id: 'popup',
    width: 500,
    layout: 'fit',
    title: 'Photo',

    items: [
        {
            xtype: 'image',
            reference: 'myimg',
            height: 830,
            width: 830
        }
    ],

    setSrc: function(url) {
            img = this.lookup("myimg");
        console.log(img);
            img.setSrc(url);

    }

});