/*
 * File: app/view/Page/Wedding.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.Wedding', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pagewedding',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel2',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'pagewedding'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-wedding.png);\n\n\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height:1024px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 1000,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 329,
                            width: 10
                        },
                        {
                            xtype: 'container',
                            height: 344,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '0 0 0 20',
                                    width: '55%',
                                    layout: {
                                        type: 'vbox',
                                        align: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 100,
                                            margin: '40 0 10 0',
                                            maxWidth: 370,
                                            minWidth: 370,
                                            width: 370,
                                            src: 'resources/images/tt-wedding.png'
                                        },
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            cls: 'h4',
                                            height: 40,
                                            hidden: true,
                                            margin: '30 0 0 0',
                                            text: 'NASI AMBENG'
                                        },
                                        {
                                            xtype: 'label',
                                            cls: 'desc',
                                            margin: '10 0 0 0',
                                            width: '95%',
                                            text: 'Our wedding services is special as we strive with commitment to make your wedding day an exclusive event. To make it your dream weddings come true. We will go thru every inch of details with best services and coordination. Your satisfaction is our priority. We offer three packages to suit within your budget.'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            cls: '',
                                            height: 35,
                                            itemId: 'reqtocontact',
                                            margin: 20,
                                            maxHeight: 35,
                                            minHeight: 35,
                                            scale: 'large',
                                            text: 'ENQUIRE'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    width: '45%',
                                    layout: {
                                        type: 'vbox',
                                        align: 'center',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            cls: 'tbrtrans',
                                            margin: '0 0 10 0',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'btntranslr',
                                                    itemId: 'mnuIntan',
                                                    icon: 'resources/images/txt-intan.png',
                                                    iconAlign: 'top',
                                                    scale: 'large',
                                                    text: ' '
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'btntranslr',
                                                    itemId: 'mnuPermata',
                                                    icon: 'resources/images/txt-permata.png',
                                                    iconAlign: 'top',
                                                    scale: 'large',
                                                    text: ' '
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'btntranslr',
                                                    itemId: 'mnuBerlian',
                                                    icon: 'resources/images/txt-berlian.png',
                                                    iconAlign: 'top',
                                                    scale: 'large',
                                                    text: ' '
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'label',
                                            cls: 'desc',
                                            html: '<strong>Our packages include</strong><br /><br />Decoration<br />Kendarat<br />Cleaning Services<br />Other Logistic Matters',
                                            style: 'line-height:1.4;'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'ctnpricolor',
            height: 250,
            html: [
                '<div class="wedding">',
                '<div><img src="resources/images/wedding/1-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/2-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/3-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/4-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/5-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/6-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/7-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/8-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/9-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/10-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/11-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/12-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/13-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/14-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/15-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/16-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/17-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/18-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/19-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/20-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/21-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/22-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/23-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/24-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/25-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/26-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/27-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/28-th.png" width="230" /></div>',
                '<div><img src="resources/images/wedding/29-th.png" width="230" /></div>',
                '</div>'
            ],
            padding: 10,
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        }
    ]

});