/*
 * File: app/view/Page/WeddingPackagePermata.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Page.WeddingPackagePermata', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pageweddingpackagepermata',

    requires: [
        'HjHRoziana.view.Page.NasiAmbengViewModel6',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'pageweddingpackagepermata'
    },
    border: false,
    cls: 'bg-ambeng',
    style: 'width:100% !important;\ndisplay:block;',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            cls: 'fullimg',
            style: 'background-image:url(resources/images/bg-weddingpackages.png);\nbackground-repeat: no-repeat;\n    background-position: center;\n    background-size: cover;\n    width: 100%;\n    height: 880px;\n    min-height:100%;\n    padding-top:10px;',
            width: '100%',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    height: 859,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: '0 20 0 0',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 90,
                                            margin: '35 0 10 0',
                                            maxHeight: 90,
                                            minHeight: 90,
                                            src: 'resources/images/tt-permata.png'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            html: '<ul> <li class="tt">MAIN DISHES</li> <li class="bl">&nbsp;</li> <li>Nasi Al madani</li> <li>Lembu Masak Kurma Kashmiri</li> <li>Lembu masak Bryani</li> <li>Ayam masak Bombay</li> <li>Sweet sour fish/ prawn Black Pepper</li> <li>Acar Nyonya</li> <li>Dal sayur</li> </ul>',
                                            margin: '0 20 0 10',
                                            style: 'text-align:left;',
                                            width: 280
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<ul> <li class="tt">SIDE DISHES</li> <li class="bl">&nbsp;</li> <li>Soto Madura</li> <li>Green Salad</li> <li>Potato salad</li> <li>Mushroom soup with butter rolls</li> </ul>',
                                            margin: '0 20 0 0',
                                            style: 'text-align:left;',
                                            width: 350
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<ul> <li class="tt">DESSERT CORNER</li> <li class="bl">&nbsp;</li> <li>Traditional Malay kueh</li> <li>Talam Kueh</li> <li>Custard puff</li> <li>Fruits tartlets</li> <li>Cream cakes</li> <li>Bubur</li> <li>Cordial drink, Tea and coffee</li> </ul>',
                                            style: 'text-align:left;',
                                            width: 350
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    cls: 'btntranswh',
                                    itemId: 'permatapdf',
                                    margin: '30 0 0 0',
                                    maxWidth: 330,
                                    width: '',
                                    icon: 'resources/images/icon-pdf.png',
                                    text: 'Download the package\'s menu'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'mnuWeddingCatering',
                                    maxWidth: 330,
                                    minWidth: 330,
                                    width: 330,
                                    scale: 'large',
                                    text: 'Back to Wedding Catering'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});