/*
 * File: app/model/Event.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Event', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],

    idProperty: 'evt_id',

    fields: [
        {
            type: 'int',
            name: 'evt_id'
        },
        {
            name: 'evt_type'
        },
        {
            type: 'date',
            name: 'evt_date',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'int',
            name: 'evt_qty'
        },
        {
       	    type: 'float',
            name: 'evt_price'
        },
        {
            name: 'evt_remarks'
        },
        {
            name: 'bal'
        },
        {
            name: 'qtybook'
        }
    ]
});