/*
 * File: app/view/Mock/Grid.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HjHRoziana.view.Mock.Grid', {
    extend: 'Ext.container.Container',
    alias: 'widget.mockgrid',

    requires: [
        'HjHRoziana.view.Mock.GridViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.view.Table'
    ],

    viewModel: {
        type: 'mockgrid'
    },
    height: 500,
    width: 800,

    items: [
        {
            xtype: 'gridpanel',
            cls: 'tbllt',
            height: 500,
            header: false,
            title: 'My Grid Panel',
            autoLoad: true,
            forceFit: false,
            store: 'bookings',
            columns: [
                {
                align: 'left',
                    xtype: 'gridcolumn',
                    border: false,
                    draggable: false,
                    flex: 2,
                    resizable: false,
                    enableColumnHide: false,
                    sortable: false,
                    dataIndex: 'evt_date',
                    formatter: 'date("D d M Y")',
                    hideable: false,
                    text: 'DATES AVAILABLE'
                },
                {
                	align: 'left',
                    xtype: 'numbercolumn',
                    border: false,
                    draggable: false,
                    flex: 1,
                    resizable: false,
                    sortable: false,
                    dataIndex: 'bal',
                    formatter: 'round(0)',
                    hideable: false,
                    text: 'SLOTS'
                },
                {
                    align: 'left',
                    xtype: 'templatecolumn',
                    flex: 1,
                    tpl: [
                        '${evt_price}'
                    ],
                    dataIndex: 'evt_price',
                    text: 'PRICE'
                },
                {
                align: 'left',
                    xtype: 'gridcolumn',
                    flex: 3,
                    cellWrap: true,
                    dataIndex: 'evt_remarks',
                    text: 'REMARKS'
                }
            ],
            viewConfig: {
                data: {
                    employees: [
                        {
                            firstName: 'John',
                            lastName: 'Doe'
                        },
                        {
                            firstName: 'Anna',
                            lastName: 'Smith'
                        },
                        {
                            firstName: 'Peter',
                            lastName: 'Jones'
                        }
                    ]
                }
            }
        }
    ]

});